// host = '172.16.153.122';	// hostname or IP address
host = 'test.mosquitto.org';	// hostname or IP address
// host = '172.16.153.110';	// hostname or IP address
port = 8080;
topic = '/bcx16';		// topic to subscribe to
useTLS = false;
username = null;
password = null;
cleansession = true;
